.conventional_commit:
  image: node:18-alpine
  stage: lint
  before_script:
  script:
    - |
        set -x
        echo "+ installing commitlint"
        apk add -u --no-cache git
        npm install -g @commitlint/cli @commitlint/config-conventional@18.6.0
        echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
    - |
        set -x
        echo "+ linting commit message"
        echo "${CI_COMMIT_MESSAGE}" | npx commitlint
