services:
  front:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        API_BASE_URL: http://conduit:8080/api/v1
    image: realworld/front
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
      name: realworld
      external: true
